### ISSUE TITLE
Update for ^0.4.23

### ISSUE THREAD

**Issue by entrptaher** [StephenGrider/EthereumCasts#5]
The `http://remix.ethereum.org` throws warning about `contstructor` on this line https://github.com/StephenGrider/EthereumCasts/blob/master/inbox/contracts/Inbox.sol#L6. 

Also truffle will fail to deploy the contract. Even though it has been only 3-4 months, the code stopped working as this is a fast paced world.

The course and code should be updated for that.

Peace.

**Comment by PoojaG20** [comment]
For constructor its just a warning , it can work then too. But for deploying the contract using truffle it is able to create contract but the status is given Fail. Any updates how to fix it.
It gives error-**"The contract could not be stored, please check your gas limit."** 
Increasing the gas limit also did not help.

**Comment by entrptaher** [comment]
@PoojaG20 This is related to this issue here. https://github.com/trufflesuite/truffle-hdwallet-provider/issues/33

Try to  `npm install --save truffle-hdwallet-provider@0.0.3`.

**Comment by PoojaG20** [comment]
Thanks @entrptaher it was version issue only but it is not 3.0.0 rather 0.0.3. 
**npm install --save truffle-hdwallet-provider@0.0.3** 
Worked

**Comment by entrptaher** [comment]
Opps, sorry, it was a typo. :D

But still the problem remains that the code should be updated for ^0.4.23

**Comment by Kanishka6996** [comment]
On deploy.js you change
.deploy({ data: compiledFactory.bytecode })

To:
.deploy({ data: '0x' + compiledFactory.bytecode })

it will work.

**Comment by entrptaher** [comment]
I feel the original repo should be updated. However this solves problem and I am gonna close the issue until the problem arises again.
